# Generated by Django 4.0.8 on 2024-10-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsandevents',
            old_name='summary_es',
            new_name='summary_fa',
        ),
        migrations.RenameField(
            model_name='newsandevents',
            old_name='title_es',
            new_name='title_fa',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='newsandevents',
            name='title_ru',
        ),
    ]
