# Generated by Django 4.0.8 on 2025-05-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_summary_es_newsandevents_summary_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If checked, this news will be visible to non-logged in users'),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='news_thumbnails/'),
        ),
    ]
