# Generated by Django 4.0.8 on 2025-05-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsandevents_is_public_newsandevents_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, comma separated (optional)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (optional, max 160 characters)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (optional)', max_length=200, null=True),
        ),
    ]
