# Generated by Django 4.0.8 on 2025-05-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsandevents_keywords_and_more'),
    ]

    operations = [
    ]
