# Generated by Django 4.0.8 on 2025-05-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250517_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsandevents',
            name='summary_fa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
