# Generated by Django 4.0.8 on 2024-10-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='summary_es',
            new_name='summary_fa',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title_es',
            new_name='title_fa',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='summary_es',
            new_name='summary_fa',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='title_es',
            new_name='title_fa',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='title_es',
            new_name='title_fa',
        ),
        migrations.RenameField(
            model_name='uploadvideo',
            old_name='summary_es',
            new_name='summary_fa',
        ),
        migrations.RenameField(
            model_name='uploadvideo',
            old_name='title_es',
            new_name='title_fa',
        ),
        migrations.RemoveField(
            model_name='course',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='title_ru',
        ),
    ]
