# Generated by Django 4.0.8 on 2024-11-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_topic_upload_topic_uploadvideo_topic'),
    ]

    operations = [
    ]
