# Generated by Django 4.0.8 on 2024-11-07 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_populate_upload_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='course.topic'),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='course.topic'),
        ),
    ]
