# Generated by Django 4.0.8 on 2024-11-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_upload_topic_alter_uploadvideo_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_fa',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
