# Generated by Django 4.0.8 on 2024-11-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_topic_title_en_topic_title_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='description',
            field=models.TextField(blank=True, help_text='Video description'),
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL'),
        ),
    ]
