# Generated by Django 4.0.8 on 2024-11-07 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_uploadvideo_description_uploadvideo_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_fa',
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video',
            field=models.FileField(blank=True, help_text='Valid video formats: mp4, mkv, wmv, 3gp, f4v, avi, mp3', null=True, upload_to='course_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'wmv', '3gp', 'f4v', 'avi', 'mp3'])]),
        ),
        migrations.AlterField(
            model_name='uploadvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL', null=True),
        ),
    ]
