# Generated by Django 4.0.8 on 2024-11-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_uploadvideo_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='description_en',
            field=models.TextField(blank=True, help_text='Video description', null=True),
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='description_fa',
            field=models.TextField(blank=True, help_text='Video description', null=True),
        ),
    ]
