# Generated by Django 4.0.8 on 2024-11-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_coursesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
    ]
