# Generated by Django 4.0.8 on 2025-01-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='FIRST', max_length=100),
        ),
    ]
