# Generated by Django 4.0.8 on 2025-05-16 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_discussiontopic_discussionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionresponse',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='course.discussionresponse'),
        ),
    ]
