# Generated by Django 4.0.8 on 2024-10-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_assignmentsubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text_es',
            new_name='choice_text_fa',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content_es',
            new_name='content_fa',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='explanation_es',
            new_name='explanation_fa',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='description_es',
            new_name='description_fa',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='title_es',
            new_name='title_fa',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text_fr',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_ru',
        ),
    ]
