# Generated by Django 4.0.8 on 2025-02-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Level course', 'Level course'), ('Middle School', 'Middle School'), ('High School', 'High School')], max_length=25, null=True),
        ),
    ]
