# Generated by Django 4.0.8 on 2025-02-22 03:32

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_unique_id',
            field=models.CharField(blank=True, default=accounts.utils.generate_student_id, max_length=50, null=True, unique=True),
        ),
    ]
