# Generated by Django 4.0.8 on 2024-10-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='description_es',
            new_name='description_fa',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='title_es',
            new_name='title_fa',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title_ru',
        ),
    ]
