# Generated by Django 4.0.8 on 2024-10-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_rename_description_es_assignment_description_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
