# Generated by Django 4.0.8 on 2024-10-31 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_temporaryuploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryUploadedFile',
        ),
    ]
