# Generated by Django 4.0.8 on 2024-11-02 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_delete_temporaryuploadedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ('deadline',)},
        ),
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='evaluation_criteria',
            field=models.FileField(upload_to='assignment/evaluation_files/'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='ai_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='final_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='teacher_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
