# Generated by Django 4.0.8 on 2024-11-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='additional_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='assignment/additional_files/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='evaluation_criteria',
            field=models.FileField(max_length=255, upload_to='assignment/evaluation_files/'),
        ),
    ]
