# Generated by Django 4.0.8 on 2024-11-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_alter_assignment_additional_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmissionfile',
            name='file',
            field=models.FileField(max_length=255, upload_to='assignment/submissions/files/'),
        ),
    ]
