# Generated by Django 4.0.8 on 2024-11-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_uploadvideo_description_en_and_more'),
        ('assignment', '0010_assignment_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='course.topic'),
        ),
    ]
